# Generated by Django 5.2.14 on 2026-05-20 18:49

import django.core.validators
from django.db import migrations, models


def add_country_code_if_missing(apps, schema_editor):
    Contact = apps.get_model('contacts', 'Contact')

    with schema_editor.connection.cursor() as cursor:
        columns = [
            column.name
            for column in schema_editor.connection.introspection.get_table_description(
                cursor,
                Contact._meta.db_table,
            )
        ]

    if 'country_code' in columns:
        return

    field = models.CharField(
        blank=True,
        max_length=5,
        null=True,
        validators=[
            django.core.validators.RegexValidator(
                message='Country code must contain only digits.',
                regex='^\\d{1,5}$',
            )
        ],
    )
    field.set_attributes_from_name('country_code')
    schema_editor.add_field(Contact, field)


def normalize_phone_numbers(apps, schema_editor):
    Contact = apps.get_model('contacts', 'Contact')

    for contact in Contact.objects.all():
        digits = ''.join(character for character in str(contact.phone_number or '') if character.isdigit())

        if len(digits) > 10:
            contact.country_code = digits[:-10][:5]
            contact.phone_number = digits[-10:]
        else:
            contact.phone_number = digits

        contact.save(update_fields=['country_code', 'phone_number'])


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(add_country_code_if_missing, migrations.RunPython.noop),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='contact',
                    name='country_code',
                    field=models.CharField(blank=True, max_length=5, null=True, validators=[django.core.validators.RegexValidator(message='Country code must contain only digits.', regex='^\\d{1,5}$')]),
                ),
            ],
        ),
        migrations.RunPython(normalize_phone_numbers, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='contact',
            name='phone_number',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Phone number must be exactly 10 digits.', regex='^\\d{10}$')]),
        ),
    ]
